/* Auto-generated by genmsg_cpp for file /tmp/buildd/ros-electric-turtlebot-apps-0.2.0/debian/ros-electric-turtlebot-apps/opt/ros/electric/stacks/turtlebot_apps/turtlebot_calibration/msg/ScanAngle.msg */
#ifndef TURTLEBOT_CALIBRATION_MESSAGE_SCANANGLE_H
#define TURTLEBOT_CALIBRATION_MESSAGE_SCANANGLE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace turtlebot_calibration
{
template <class ContainerAllocator>
struct ScanAngle_ {
  typedef ScanAngle_<ContainerAllocator> Type;

  ScanAngle_()
  : header()
  , scan_angle(0.0)
  {
  }

  ScanAngle_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , scan_angle(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _scan_angle_type;
  double scan_angle;


private:
  static const char* __s_getDataType_() { return "turtlebot_calibration/ScanAngle"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "06e2c839dc5c7f5c13ac09a8b4ff0a6a"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
float64 scan_angle\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, scan_angle);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, scan_angle);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(scan_angle);
    return size;
  }

  typedef boost::shared_ptr< ::turtlebot_calibration::ScanAngle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot_calibration::ScanAngle_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ScanAngle
typedef  ::turtlebot_calibration::ScanAngle_<std::allocator<void> > ScanAngle;

typedef boost::shared_ptr< ::turtlebot_calibration::ScanAngle> ScanAnglePtr;
typedef boost::shared_ptr< ::turtlebot_calibration::ScanAngle const> ScanAngleConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::turtlebot_calibration::ScanAngle_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::turtlebot_calibration::ScanAngle_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace turtlebot_calibration

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::turtlebot_calibration::ScanAngle_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::turtlebot_calibration::ScanAngle_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::turtlebot_calibration::ScanAngle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "06e2c839dc5c7f5c13ac09a8b4ff0a6a";
  }

  static const char* value(const  ::turtlebot_calibration::ScanAngle_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x06e2c839dc5c7f5cULL;
  static const uint64_t static_value2 = 0x13ac09a8b4ff0a6aULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot_calibration::ScanAngle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "turtlebot_calibration/ScanAngle";
  }

  static const char* value(const  ::turtlebot_calibration::ScanAngle_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::turtlebot_calibration::ScanAngle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float64 scan_angle\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::turtlebot_calibration::ScanAngle_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::turtlebot_calibration::ScanAngle_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::turtlebot_calibration::ScanAngle_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::turtlebot_calibration::ScanAngle_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.scan_angle);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ScanAngle_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot_calibration::ScanAngle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::turtlebot_calibration::ScanAngle_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "scan_angle: ";
    Printer<double>::stream(s, indent + "  ", v.scan_angle);
  }
};


} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT_CALIBRATION_MESSAGE_SCANANGLE_H

