"""autogenerated by genmsg_py from Enabled.msg. Do not edit."""
import roslib.message
import struct


class Enabled(roslib.message.Message):
  _md5sum = "944b9b58b23f7416adecf8816d3ed0ef"
  _type = "rover_msgs/Enabled"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool motorsEnabled
bool settingsDumpEnabled

"""
  __slots__ = ['motorsEnabled','settingsDumpEnabled']
  _slot_types = ['bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       motorsEnabled,settingsDumpEnabled
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(Enabled, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.motorsEnabled is None:
        self.motorsEnabled = False
      if self.settingsDumpEnabled is None:
        self.settingsDumpEnabled = False
    else:
      self.motorsEnabled = False
      self.settingsDumpEnabled = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_2B.pack(_x.motorsEnabled, _x.settingsDumpEnabled))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.motorsEnabled, _x.settingsDumpEnabled,) = _struct_2B.unpack(str[start:end])
      self.motorsEnabled = bool(self.motorsEnabled)
      self.settingsDumpEnabled = bool(self.settingsDumpEnabled)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_2B.pack(_x.motorsEnabled, _x.settingsDumpEnabled))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.motorsEnabled, _x.settingsDumpEnabled,) = _struct_2B.unpack(str[start:end])
      self.motorsEnabled = bool(self.motorsEnabled)
      self.settingsDumpEnabled = bool(self.settingsDumpEnabled)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_2B = struct.Struct("<2B")
