"""autogenerated by genmsg_py from Settings.msg. Do not edit."""
import roslib.message
import struct

import std_msgs.msg

class Settings(roslib.message.Message):
  _md5sum = "c0d59de285a4827280115b3f83474657"
  _type = "rover_msgs/Settings"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

float32 left_proportional
float32 left_integral
float32 left_derivative
float32 left_conversion_factor

float32 right_proportional
float32 right_integral
float32 right_derivative
float32 right_conversion_factor

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['header','left_proportional','left_integral','left_derivative','left_conversion_factor','right_proportional','right_integral','right_derivative','right_conversion_factor']
  _slot_types = ['Header','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       header,left_proportional,left_integral,left_derivative,left_conversion_factor,right_proportional,right_integral,right_derivative,right_conversion_factor
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(Settings, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg._Header.Header()
      if self.left_proportional is None:
        self.left_proportional = 0.
      if self.left_integral is None:
        self.left_integral = 0.
      if self.left_derivative is None:
        self.left_derivative = 0.
      if self.left_conversion_factor is None:
        self.left_conversion_factor = 0.
      if self.right_proportional is None:
        self.right_proportional = 0.
      if self.right_integral is None:
        self.right_integral = 0.
      if self.right_derivative is None:
        self.right_derivative = 0.
      if self.right_conversion_factor is None:
        self.right_conversion_factor = 0.
    else:
      self.header = std_msgs.msg._Header.Header()
      self.left_proportional = 0.
      self.left_integral = 0.
      self.left_derivative = 0.
      self.left_conversion_factor = 0.
      self.right_proportional = 0.
      self.right_integral = 0.
      self.right_derivative = 0.
      self.right_conversion_factor = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_8f.pack(_x.left_proportional, _x.left_integral, _x.left_derivative, _x.left_conversion_factor, _x.right_proportional, _x.right_integral, _x.right_derivative, _x.right_conversion_factor))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg._Header.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.left_proportional, _x.left_integral, _x.left_derivative, _x.left_conversion_factor, _x.right_proportional, _x.right_integral, _x.right_derivative, _x.right_conversion_factor,) = _struct_8f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_8f.pack(_x.left_proportional, _x.left_integral, _x.left_derivative, _x.left_conversion_factor, _x.right_proportional, _x.right_integral, _x.right_derivative, _x.right_conversion_factor))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg._Header.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.left_proportional, _x.left_integral, _x.left_derivative, _x.left_conversion_factor, _x.right_proportional, _x.right_integral, _x.right_derivative, _x.right_conversion_factor,) = _struct_8f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_3I = struct.Struct("<3I")
_struct_8f = struct.Struct("<8f")
