/* Auto-generated by genmsg_cpp for file /home/rbtying/robot/rover_msgs/msg/Gyro.msg */
#ifndef ROVER_MSGS_MESSAGE_GYRO_H
#define ROVER_MSGS_MESSAGE_GYRO_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace rover_msgs
{
template <class ContainerAllocator>
struct Gyro_ {
  typedef Gyro_<ContainerAllocator> Type;

  Gyro_()
  : header()
  , rate(0.0)
  , value(0.0)
  {
  }

  Gyro_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , rate(0.0)
  , value(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _rate_type;
  float rate;

  typedef float _value_type;
  float value;


private:
  static const char* __s_getDataType_() { return "rover_msgs/Gyro"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "b333db2883ae55e6bf4cf64f69ef72df"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
float32 rate\n\
float32 value\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, rate);
    ros::serialization::serialize(stream, value);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, rate);
    ros::serialization::deserialize(stream, value);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(rate);
    size += ros::serialization::serializationLength(value);
    return size;
  }

  typedef boost::shared_ptr< ::rover_msgs::Gyro_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_msgs::Gyro_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Gyro
typedef  ::rover_msgs::Gyro_<std::allocator<void> > Gyro;

typedef boost::shared_ptr< ::rover_msgs::Gyro> GyroPtr;
typedef boost::shared_ptr< ::rover_msgs::Gyro const> GyroConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::rover_msgs::Gyro_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::rover_msgs::Gyro_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace rover_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rover_msgs::Gyro_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rover_msgs::Gyro_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rover_msgs::Gyro_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b333db2883ae55e6bf4cf64f69ef72df";
  }

  static const char* value(const  ::rover_msgs::Gyro_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb333db2883ae55e6ULL;
  static const uint64_t static_value2 = 0xbf4cf64f69ef72dfULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_msgs::Gyro_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rover_msgs/Gyro";
  }

  static const char* value(const  ::rover_msgs::Gyro_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rover_msgs::Gyro_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float32 rate\n\
float32 value\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::rover_msgs::Gyro_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::rover_msgs::Gyro_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::rover_msgs::Gyro_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rover_msgs::Gyro_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.rate);
    stream.next(m.value);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Gyro_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_msgs::Gyro_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::rover_msgs::Gyro_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "rate: ";
    Printer<float>::stream(s, indent + "  ", v.rate);
    s << indent << "value: ";
    Printer<float>::stream(s, indent + "  ", v.value);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROVER_MSGS_MESSAGE_GYRO_H

