/* Auto-generated by genmsg_cpp for file /home/rbtying/robot/rover_msgs/msg/Settings.msg */
#ifndef ROVER_MSGS_MESSAGE_SETTINGS_H
#define ROVER_MSGS_MESSAGE_SETTINGS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace rover_msgs
{
template <class ContainerAllocator>
struct Settings_ {
  typedef Settings_<ContainerAllocator> Type;

  Settings_()
  : header()
  , left_proportional(0.0)
  , left_integral(0.0)
  , left_derivative(0.0)
  , left_conversion_factor(0.0)
  , right_proportional(0.0)
  , right_integral(0.0)
  , right_derivative(0.0)
  , right_conversion_factor(0.0)
  {
  }

  Settings_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , left_proportional(0.0)
  , left_integral(0.0)
  , left_derivative(0.0)
  , left_conversion_factor(0.0)
  , right_proportional(0.0)
  , right_integral(0.0)
  , right_derivative(0.0)
  , right_conversion_factor(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _left_proportional_type;
  float left_proportional;

  typedef float _left_integral_type;
  float left_integral;

  typedef float _left_derivative_type;
  float left_derivative;

  typedef float _left_conversion_factor_type;
  float left_conversion_factor;

  typedef float _right_proportional_type;
  float right_proportional;

  typedef float _right_integral_type;
  float right_integral;

  typedef float _right_derivative_type;
  float right_derivative;

  typedef float _right_conversion_factor_type;
  float right_conversion_factor;


private:
  static const char* __s_getDataType_() { return "rover_msgs/Settings"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "c0d59de285a4827280115b3f83474657"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
\n\
float32 left_proportional\n\
float32 left_integral\n\
float32 left_derivative\n\
float32 left_conversion_factor\n\
\n\
float32 right_proportional\n\
float32 right_integral\n\
float32 right_derivative\n\
float32 right_conversion_factor\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, left_proportional);
    ros::serialization::serialize(stream, left_integral);
    ros::serialization::serialize(stream, left_derivative);
    ros::serialization::serialize(stream, left_conversion_factor);
    ros::serialization::serialize(stream, right_proportional);
    ros::serialization::serialize(stream, right_integral);
    ros::serialization::serialize(stream, right_derivative);
    ros::serialization::serialize(stream, right_conversion_factor);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, left_proportional);
    ros::serialization::deserialize(stream, left_integral);
    ros::serialization::deserialize(stream, left_derivative);
    ros::serialization::deserialize(stream, left_conversion_factor);
    ros::serialization::deserialize(stream, right_proportional);
    ros::serialization::deserialize(stream, right_integral);
    ros::serialization::deserialize(stream, right_derivative);
    ros::serialization::deserialize(stream, right_conversion_factor);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(left_proportional);
    size += ros::serialization::serializationLength(left_integral);
    size += ros::serialization::serializationLength(left_derivative);
    size += ros::serialization::serializationLength(left_conversion_factor);
    size += ros::serialization::serializationLength(right_proportional);
    size += ros::serialization::serializationLength(right_integral);
    size += ros::serialization::serializationLength(right_derivative);
    size += ros::serialization::serializationLength(right_conversion_factor);
    return size;
  }

  typedef boost::shared_ptr< ::rover_msgs::Settings_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_msgs::Settings_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Settings
typedef  ::rover_msgs::Settings_<std::allocator<void> > Settings;

typedef boost::shared_ptr< ::rover_msgs::Settings> SettingsPtr;
typedef boost::shared_ptr< ::rover_msgs::Settings const> SettingsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::rover_msgs::Settings_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::rover_msgs::Settings_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace rover_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rover_msgs::Settings_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rover_msgs::Settings_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rover_msgs::Settings_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c0d59de285a4827280115b3f83474657";
  }

  static const char* value(const  ::rover_msgs::Settings_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc0d59de285a48272ULL;
  static const uint64_t static_value2 = 0x80115b3f83474657ULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_msgs::Settings_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rover_msgs/Settings";
  }

  static const char* value(const  ::rover_msgs::Settings_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rover_msgs::Settings_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
float32 left_proportional\n\
float32 left_integral\n\
float32 left_derivative\n\
float32 left_conversion_factor\n\
\n\
float32 right_proportional\n\
float32 right_integral\n\
float32 right_derivative\n\
float32 right_conversion_factor\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::rover_msgs::Settings_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::rover_msgs::Settings_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::rover_msgs::Settings_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rover_msgs::Settings_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.left_proportional);
    stream.next(m.left_integral);
    stream.next(m.left_derivative);
    stream.next(m.left_conversion_factor);
    stream.next(m.right_proportional);
    stream.next(m.right_integral);
    stream.next(m.right_derivative);
    stream.next(m.right_conversion_factor);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Settings_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_msgs::Settings_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::rover_msgs::Settings_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_proportional: ";
    Printer<float>::stream(s, indent + "  ", v.left_proportional);
    s << indent << "left_integral: ";
    Printer<float>::stream(s, indent + "  ", v.left_integral);
    s << indent << "left_derivative: ";
    Printer<float>::stream(s, indent + "  ", v.left_derivative);
    s << indent << "left_conversion_factor: ";
    Printer<float>::stream(s, indent + "  ", v.left_conversion_factor);
    s << indent << "right_proportional: ";
    Printer<float>::stream(s, indent + "  ", v.right_proportional);
    s << indent << "right_integral: ";
    Printer<float>::stream(s, indent + "  ", v.right_integral);
    s << indent << "right_derivative: ";
    Printer<float>::stream(s, indent + "  ", v.right_derivative);
    s << indent << "right_conversion_factor: ";
    Printer<float>::stream(s, indent + "  ", v.right_conversion_factor);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROVER_MSGS_MESSAGE_SETTINGS_H

