<?xml version="1.0" ?>

<robot name="rover" xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <!-- Colors -->
    <xacro:macro name="color_blue">
        <material name="blue">
            <color rgba="0 0 0.75 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_yellow">
        <material name="yellow">
            <color rgba="0.75 0.75 0 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_red_green">
        <material name="red_green">
            <color rgba="1.0 1.0 0 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_black">
        <material name="black">
            <color rgba="0.1 0.1 0.1 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_dark_gray">
        <material name="dark_gray">
            <color rgba="0.3 0.3 0.3 1.0" />
        </material>
    </xacro:macro>
    
    <xacro:macro name="color_gray">
        <material name="gray">
            <color rgba="0.5 0.5 0.5 1.0" />
        </material>
    </xacro:macro>
    
    <xacro:macro name="color_silver">
        <material name="silver">
            <color rgba="0.9 0.9 0.9 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_green">
        <material name="green">
            <color rgba="0 0.75 0.1 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_olive">
        <material name="olive">
            <color rgba="0.5 0.5 0 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_orange">
        <material name="orange">
            <color rgba="1.0 0.65 0 1.0" />
        </material>
    </xacro:macro>
    
    <xacro:macro name="color_aqua">
        <material name="aqua">
            <color rgba="0.25 0.3 0 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_dark_purple">
        <material name="dark_purple">
            <color rgba="0.3 0 0.3 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_magenta">
        <material name="magenta">
            <color rgba="1.0 0 1.0 0.5" />
        </material>
    </xacro:macro>
    
    <!-- useful macros -->
    <xacro:macro name="prism" params="name x y z *color">
        <link name="${name}">
            <visual>
                <geometry>
                    <box size="${x} ${y} ${z}" />
                </geometry>
                <xacro:insert_block name="color" />
            </visual>
            <collision>
                <geometry>
                    <box size="${x} ${y} ${z}" />
                </geometry>
            </collision>
        </link>
    </xacro:macro>

    <xacro:macro name="cyl" params="name radius length *color">
        <link name="${name}">
            <visual>
                <geometry>
                    <cylinder radius="${radius}" length="${length}" />
                </geometry>
                <xacro:insert_block name="color" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${radius}" length="${length}" />
                </geometry>
            </collision>
        </link>
    </xacro:macro>

    <xacro:property name="wheel_diameter" value="0.07265" />
    <xacro:property name="wheel_thickness" value="0.02" />
    <xacro:property name="motor_length" value="0.055" />
    <xacro:macro name="wheel" params="name parent offsetx offsety offsetz side">
        <xacro:cyl name="${name}" radius="${wheel_diameter / 2}" length="${wheel_thickness - 0.001}">
            <xacro:color_orange />
        </xacro:cyl>
        <xacro:cyl name="${name}_inner" radius="${(wheel_diameter / 2) - 0.0075}" length="${wheel_thickness}">
            <xacro:color_black />
        </xacro:cyl>
        <xacro:cyl name="${name}_motor" radius="0.0185" length="${motor_length}">
            <xacro:color_silver />
        </xacro:cyl>
        <xacro:cyl name="${name}_motor_axle" radius="0.003" length="0.01">
            <xacro:color_silver />
        </xacro:cyl>
        <joint name="${name}_motor_joint" type="fixed">
            <parent link="${parent}" />
            <child link="${name}_motor" />
            <origin xyz="${offsetx} ${offsety + side * (0.01 + motor_length / 2)} ${offsetz}" rpy="${halfpi * side} 0 0" />
        </joint>
        <joint name="${name}_motor_axle_joint" type="fixed">
            <parent link="${name}_motor" />
            <child link="${name}_motor_axle" />
            <axis xyz="0 1 0" />
            <origin xyz="0 0 ${((motor_length + 0.01) / 2)}" rpy="0 0 0" />
        </joint>
        <joint name="${name}_joint" type="fixed">
            <parent link="${name}_motor_axle" />
            <child link="${name}" />
            <axis xyz="0 1 0" />
            <origin xyz="0 0 ${((0.01 + wheel_thickness) / 2)}" rpy="0 0 0" />
        </joint>
        <joint name="${name}_inner_joint" type="fixed">
            <parent link="${name}" />
            <child link="${name}_inner" />
            <origin xyz="0 0 0" rpy="0 0 0" />
        </joint>
    </xacro:macro>

    <!-- Links --> 
    <link name="base_link" />
    <link name="base_footprint" />
    
    <!-- useful definition -->
    <xacro:property name="halfpi" value="1.57079633" />
    <xacro:property name="sixthpi" value="0.523598776" />

    <!-- Robot movement base representation -->
    <xacro:property name="robot_base_height" value="0.065" />
    <xacro:property name="robot_base_length" value="0.30" />
    <xacro:property name="robot_base_width" value="0.32" />
    <xacro:prism name="robot_base" x="${robot_base_length}" y="${robot_base_width}" z="${robot_base_height}">
        <xacro:color_dark_gray />
    </xacro:prism>
    <xacro:prism name="robot_back_left" x="0.01" y="0.01" z="0.245">
        <xacro:color_gray />
    </xacro:prism>
    <xacro:prism name="robot_back_right" x="0.01" y="0.01" z="0.245">
        <xacro:color_gray />
    </xacro:prism>
    <xacro:prism name="robot_back_top" x="0.01" y="${robot_base_width}" z="0.01">
        <xacro:color_gray />
    </xacro:prism>

    <xacro:property name="laptop_length" value="0.19" />
    <xacro:property name="laptop_width" value="0.265" />
    <xacro:prism name="laptop_lid" x="${laptop_length}" y="${laptop_width}" z="0.0075">
        <xacro:color_blue />
    </xacro:prism>
    <xacro:prism name="laptop_base" x="${laptop_length}" y="${laptop_width}" z="0.02">
        <xacro:color_blue />
    </xacro:prism>

    <xacro:property name="fwd_offset" value="-.105" />
    <xacro:property name="wid_offset" value=".155" />
    <xacro:property name="height_offset" value=".065" />

    <!-- wheels and locomotion -->
    <xacro:wheel name="left_wheel" parent="base_link" offsetx="0" offsety="0.1175" offsetz="${wheel_diameter / 2}" side="-1" />
    <xacro:wheel name="right_wheel" parent="base_link" offsetx="0" offsety="-0.1175" offsetz="${wheel_diameter / 2}" side="1" />
    <xacro:cyl name="caster" radius="0.025" length="0.025">
        <xacro:color_black />
    </xacro:cyl>
    <joint name="caster_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster" />
        <origin xyz="${fwd_offset - 0.10} 0 0.025" rpy="${halfpi} 0 0" />
    </joint>
    
    <!-- kinect representation -->
    <xacro:prism name="openni_camera" x="0.06" y="0.285" z="0.035">
        <xacro:color_black />
    </xacro:prism>

    <!-- Joints -->
    <joint name="nav_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 0" />
    </joint>
    <joint name="base_joint" type="fixed">
        <parent link="base_link" />
        <child link="robot_base" />
        <origin xyz="${fwd_offset} 0 ${height_offset + (robot_base_height / 2)}" rpy="0 0 0" />
    </joint>

    <joint name="back_left_joint" type="fixed">
        <parent link="robot_base" />
        <child link="robot_back_left" />
        <origin xyz="${0.005 - robot_base_length / 2} ${robot_base_width / 2 - 0.005} ${0.245 / 2 + robot_base_height / 2}" rpy="0 0 0" />
    </joint>
    
    <joint name="back_right_joint" type="fixed">
        <parent link="robot_base" />
        <child link="robot_back_right" />
        <origin xyz="${0.005 - robot_base_length / 2} -${robot_base_width / 2 - 0.005} ${0.245 / 2 + robot_base_height / 2}" rpy="0 0 0" />
    </joint>

    <joint name="back_top_joint" type="fixed">
        <parent link="robot_base" />
        <child link="robot_back_top" />
        <origin xyz="${0.005 - robot_base_length / 2} 0 ${0.24 + robot_base_height / 2}" rpy="0 0 0" />
    </joint>

    <joint name="laptop_joint" type="fixed">
        <parent link="robot_base" />
        <child link="laptop_base" />
        <origin xyz="0.045 0 ${0.01 + robot_base_height / 2}" rpy="0 0 0" />
    </joint>

    <joint name="lid_joint" type="fixed">
        <parent link="laptop_base" />
        <child link="laptop_lid" />
        <origin xyz="-${laptop_length / 2 + laptop_length / 4} 0 ${laptop_length * 0.866025404 /2 + 0.01}" rpy="0 ${halfpi - sixthpi} 0" />
    </joint>

    <joint name="kinect_joint" type="fixed">
        <parent link="robot_base" />
        <child link="openni_camera" />
        <origin xyz="-0.13 0 ${0.22 + robot_base_height / 2}" rpy="0 0 0" />
    </joint>

</robot>
