<?xml version="1.0" ?>

<robot name="rover" xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <!-- Colors -->
    <xacro:macro name="color_blue">
        <material name="blue">
            <color rgba="0 0 0.75 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_yellow">
        <material name="yellow">
            <color rgba="0.75 0.75 0 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_red_green">
        <material name="red_green">
            <color rgba="1.0 1.0 0 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_dark_gray">
        <material name="dark_gray">
            <color rgba="0.3 0.3 0.3 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_green">
        <material name="green">
            <color rgba="0 0.75 0.1 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_olive">
        <material name="olive">
            <color rgba="0.5 0.5 0 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_aqua">
        <material name="aqua">
            <color rgba="0.25 0.3 0 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_dark_purple">
        <material name="dark_purple">
            <color rgba="0.3 0 0.3 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_magenta">
        <material name="magenta">
            <color rgba="1.0 0 1.0 0.5" />
        </material>
    </xacro:macro>
    
    <!-- useful macros -->
    <xacro:macro name="prism" params="name x y z *color">
        <link name="${name}">
            <visual>
                <geometry>
                    <box size="${x} ${y} ${z}" />
                </geometry>
                <xacro:insert_block name="color" />
            </visual>
            <collision>
                <geometry>
                    <box size="${x} ${y} ${z}" />
                </geometry>
            </collision>
        </link>
    </xacro:macro>

    <xacro:macro name="cyl" params="name radius length *color">
        <link name="${name}">
            <visual>
                <geometry>
                    <cylinder radius="${radius}" length="${length}" />
                </geometry>
                <xacro:insert_block name="color" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${radius}" length="${length}" />
                </geometry>
            </collision>
        </link>
    </xacro:macro>

    <xacro:macro name="tslot_x" params="prefix length">
        <xacro:prism name="${prefix}_x_tslot" x="${length}" y="0.01" z="0.01">
            <xacro:color_dark_gray />
        </xacro:prism>
    </xacro:macro>
    
    <xacro:macro name="tslot_y" params="prefix length">
        <xacro:prism name="${prefix}_y_tslot" x="0.01" y="${length}" z="0.01">
            <xacro:color_dark_gray />
        </xacro:prism>
    </xacro:macro>

    <xacro:macro name="tslot_z" params="prefix length">
        <xacro:prism name="${prefix}_z_tslot" x="0.01" y="0.01" z="${length}">
            <xacro:color_dark_gray />
        </xacro:prism>
    </xacro:macro>

    <!-- Links --> 
    <link name="base_footprint" />
    <link name="base_link" />

    <!-- Robot movement base representation -->
    <xacro:prism name="robot_base" x="0.30" y="0.24" z="0.01">
        <xacro:color_blue />
    </xacro:prism>

    <!-- Robot tslot frame -->
    <xacro:tslot_x prefix="lb" length="0.30" />
    <xacro:tslot_x prefix="lt" length="0.28" />
    <xacro:tslot_x prefix="rb" length="0.30" />
    <xacro:tslot_x prefix="rt" length="0.28" />
    <xacro:tslot_y prefix="fb" length="0.30" />
    <xacro:tslot_y prefix="ft" length="0.30" />
    <xacro:tslot_y prefix="rt" length="0.30" />
    <xacro:tslot_y prefix="rb" length="0.30" />
    <xacro:tslot_z prefix="lf" length="0.30" />
    <xacro:tslot_z prefix="lb" length="0.30" />
    <xacro:tslot_z prefix="rf" length="0.30" />
    <xacro:tslot_z prefix="rb" length="0.30" />

    <!-- useful definition -->
    <xacro:property name="halfpi" value="1.57079633" />

    <!-- frame joints -->
    <xacro:property name="fwd_offset" value="-.105" />
    <xacro:property name="wid_offset" value=".155" />
    <xacro:property name="height_offset" value=".07" />

    <joint name="base_joint" type="fixed">
        <parent link="base_link" />
        <child link="robot_base" />
        <origin xyz="${fwd_offset} 0 ${height_offset}" rpy="0 0 0" />
    </joint>
    <joint name="lbx" type="fixed">
        <parent link="base_link" />
        <child link="lb_x_tslot" />
        <origin xyz="${fwd_offset} -${wid_offset} ${height_offset}" rpy="0 0 0" />
    </joint>
    <joint name="ltx" type="fixed">
        <parent link="base_link" />
        <child link="lt_x_tslot" />
        <origin xyz="${fwd_offset + .005} -${wid_offset} ${height_offset + 0.29}" rpy="0 0 0" />
    </joint>
    <joint name="rbx" type="fixed">
        <parent link="base_link" />
        <child link="rb_x_tslot" />
        <origin xyz="${fwd_offset} ${wid_offset} ${height_offset}" rpy="0 0 0" />
    </joint>
    <joint name="rtx" type="fixed">
        <parent link="base_link" />
        <child link="rt_x_tslot" />
        <origin xyz="${fwd_offset + .005} ${wid_offset} ${height_offset + .29}" rpy="0 0 0" />
    </joint>
    <joint name="fby" type="fixed">
        <parent link="base_link" />
        <child link="fb_y_tslot" />
        <origin xyz="${fwd_offset + .15} 0 ${height_offset}" rpy="0 0 0" />
    </joint>
    <joint name="fty" type="fixed">
        <parent link="base_link" />
        <child link="ft_y_tslot" />
        <origin xyz="${fwd_offset + .15} 0 ${height_offset + .29}" rpy="0 0 0" />
    </joint>
    <joint name="rby" type="fixed">
        <parent link="base_link" />
        <child link="rb_y_tslot" />
        <origin xyz="${fwd_offset - .15} 0 ${height_offset}" rpy="0 0 0" />
    </joint>
    <joint name="rty" type="fixed">
        <parent link="base_link" />
        <child link="rt_y_tslot" />
        <origin xyz="${fwd_offset - .15} 0 ${height_offset + .29}" rpy="0 0 0" />
    </joint>
    <joint name="lfz" type="fixed">
        <parent link="base_link" />
        <child link="lf_z_tslot" />
        <origin xyz="${fwd_offset + .15} -${wid_offset} ${height_offset + .15}" rpy="0 0 0" />
    </joint>
    <joint name="lbz" type="fixed">
        <parent link="base_link" />
        <child link="lb_z_tslot" />
        <origin xyz="${fwd_offset - .15} -${wid_offset} ${height_offset + .15}" rpy="0 0 0" />
    </joint>
    <joint name="rfz" type="fixed">
        <parent link="base_link" />
        <child link="rf_z_tslot" />
        <origin xyz="${fwd_offset + .15} ${wid_offset} ${height_offset + .15}" rpy="0 0 0" />
    </joint>
    <joint name="rbz" type="fixed">
        <parent link="base_link" />
        <child link="rb_z_tslot" />
        <origin xyz="${fwd_offset - .15} ${wid_offset} ${height_offset + .15}" rpy="0 0 0" />
    </joint>

    <!-- kinect representation -->
    <xacro:prism name="kinect_base" x="0.06" y="0.075" z="0.03">
        <xacro:color_dark_purple />
    </xacro:prism>

    <xacro:prism name="openni_camera" x="0.06" y="0.285" z="0.035">
        <xacro:color_magenta />
    </xacro:prism>

    <!-- Joints -->

    <joint name="base_link_footprint_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <joint name="kinect_base_joint" type="fixed">
        <parent link="base_link" />
        <child link="kinect_base" />
        <origin xyz="0.015 0 0.115" rpy="0 0 0" />
    </joint>

    <joint name="kinect_joint" type="fixed">
        <parent link="kinect_base" />
        <child link="openni_camera" />
        <origin xyz="0 0 0.0375" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <!--<limit effort="1000.0" lower="-0.523598776" upper="0.523598776" velocity="0.5" />-->
    </joint>

</robot>
