/* Auto-generated by genmsg_cpp for file /home/rbtying/robot/rover/msg/CondensedIMU.msg */
#ifndef ROVER_MESSAGE_CONDENSEDIMU_H
#define ROVER_MESSAGE_CONDENSEDIMU_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace rover
{
template <class ContainerAllocator>
struct CondensedIMU_ {
  typedef CondensedIMU_<ContainerAllocator> Type;

  CondensedIMU_()
  : header()
  , roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  , gyro_x(0.0)
  , gyro_y(0.0)
  , gyro_z(0.0)
  , accel_x(0.0)
  , accel_y(0.0)
  , accel_z(0.0)
  , mag_heading(0.0)
  {
  }

  CondensedIMU_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  , gyro_x(0.0)
  , gyro_y(0.0)
  , gyro_z(0.0)
  , accel_x(0.0)
  , accel_y(0.0)
  , accel_z(0.0)
  , mag_heading(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _roll_type;
  float roll;

  typedef float _pitch_type;
  float pitch;

  typedef float _yaw_type;
  float yaw;

  typedef float _gyro_x_type;
  float gyro_x;

  typedef float _gyro_y_type;
  float gyro_y;

  typedef float _gyro_z_type;
  float gyro_z;

  typedef float _accel_x_type;
  float accel_x;

  typedef float _accel_y_type;
  float accel_y;

  typedef float _accel_z_type;
  float accel_z;

  typedef float _mag_heading_type;
  float mag_heading;


private:
  static const char* __s_getDataType_() { return "rover/CondensedIMU"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "38b4f3e2e1a67f0124fca6e99619cb65"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
float32 roll\n\
float32 pitch\n\
float32 yaw\n\
float32 gyro_x\n\
float32 gyro_y\n\
float32 gyro_z\n\
float32 accel_x\n\
float32 accel_y\n\
float32 accel_z\n\
float32 mag_heading\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, roll);
    ros::serialization::serialize(stream, pitch);
    ros::serialization::serialize(stream, yaw);
    ros::serialization::serialize(stream, gyro_x);
    ros::serialization::serialize(stream, gyro_y);
    ros::serialization::serialize(stream, gyro_z);
    ros::serialization::serialize(stream, accel_x);
    ros::serialization::serialize(stream, accel_y);
    ros::serialization::serialize(stream, accel_z);
    ros::serialization::serialize(stream, mag_heading);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, roll);
    ros::serialization::deserialize(stream, pitch);
    ros::serialization::deserialize(stream, yaw);
    ros::serialization::deserialize(stream, gyro_x);
    ros::serialization::deserialize(stream, gyro_y);
    ros::serialization::deserialize(stream, gyro_z);
    ros::serialization::deserialize(stream, accel_x);
    ros::serialization::deserialize(stream, accel_y);
    ros::serialization::deserialize(stream, accel_z);
    ros::serialization::deserialize(stream, mag_heading);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(roll);
    size += ros::serialization::serializationLength(pitch);
    size += ros::serialization::serializationLength(yaw);
    size += ros::serialization::serializationLength(gyro_x);
    size += ros::serialization::serializationLength(gyro_y);
    size += ros::serialization::serializationLength(gyro_z);
    size += ros::serialization::serializationLength(accel_x);
    size += ros::serialization::serializationLength(accel_y);
    size += ros::serialization::serializationLength(accel_z);
    size += ros::serialization::serializationLength(mag_heading);
    return size;
  }

  typedef boost::shared_ptr< ::rover::CondensedIMU_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover::CondensedIMU_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct CondensedIMU
typedef  ::rover::CondensedIMU_<std::allocator<void> > CondensedIMU;

typedef boost::shared_ptr< ::rover::CondensedIMU> CondensedIMUPtr;
typedef boost::shared_ptr< ::rover::CondensedIMU const> CondensedIMUConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::rover::CondensedIMU_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::rover::CondensedIMU_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace rover

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rover::CondensedIMU_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rover::CondensedIMU_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rover::CondensedIMU_<ContainerAllocator> > {
  static const char* value() 
  {
    return "38b4f3e2e1a67f0124fca6e99619cb65";
  }

  static const char* value(const  ::rover::CondensedIMU_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x38b4f3e2e1a67f01ULL;
  static const uint64_t static_value2 = 0x24fca6e99619cb65ULL;
};

template<class ContainerAllocator>
struct DataType< ::rover::CondensedIMU_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rover/CondensedIMU";
  }

  static const char* value(const  ::rover::CondensedIMU_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rover::CondensedIMU_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float32 roll\n\
float32 pitch\n\
float32 yaw\n\
float32 gyro_x\n\
float32 gyro_y\n\
float32 gyro_z\n\
float32 accel_x\n\
float32 accel_y\n\
float32 accel_z\n\
float32 mag_heading\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::rover::CondensedIMU_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::rover::CondensedIMU_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::rover::CondensedIMU_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rover::CondensedIMU_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.roll);
    stream.next(m.pitch);
    stream.next(m.yaw);
    stream.next(m.gyro_x);
    stream.next(m.gyro_y);
    stream.next(m.gyro_z);
    stream.next(m.accel_x);
    stream.next(m.accel_y);
    stream.next(m.accel_z);
    stream.next(m.mag_heading);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CondensedIMU_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover::CondensedIMU_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::rover::CondensedIMU_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "gyro_x: ";
    Printer<float>::stream(s, indent + "  ", v.gyro_x);
    s << indent << "gyro_y: ";
    Printer<float>::stream(s, indent + "  ", v.gyro_y);
    s << indent << "gyro_z: ";
    Printer<float>::stream(s, indent + "  ", v.gyro_z);
    s << indent << "accel_x: ";
    Printer<float>::stream(s, indent + "  ", v.accel_x);
    s << indent << "accel_y: ";
    Printer<float>::stream(s, indent + "  ", v.accel_y);
    s << indent << "accel_z: ";
    Printer<float>::stream(s, indent + "  ", v.accel_z);
    s << indent << "mag_heading: ";
    Printer<float>::stream(s, indent + "  ", v.mag_heading);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROVER_MESSAGE_CONDENSEDIMU_H

