/* Auto-generated by genmsg_cpp for file /home/rbtying/robot/rover/msg/Enabled.msg */
#ifndef ROVER_MESSAGE_ENABLED_H
#define ROVER_MESSAGE_ENABLED_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace rover
{
template <class ContainerAllocator>
struct Enabled_ {
  typedef Enabled_<ContainerAllocator> Type;

  Enabled_()
  : motorsEnabled(false)
  , settingsDumpEnabled(false)
  {
  }

  Enabled_(const ContainerAllocator& _alloc)
  : motorsEnabled(false)
  , settingsDumpEnabled(false)
  {
  }

  typedef uint8_t _motorsEnabled_type;
  uint8_t motorsEnabled;

  typedef uint8_t _settingsDumpEnabled_type;
  uint8_t settingsDumpEnabled;


private:
  static const char* __s_getDataType_() { return "rover/Enabled"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "944b9b58b23f7416adecf8816d3ed0ef"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "bool motorsEnabled\n\
bool settingsDumpEnabled\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, motorsEnabled);
    ros::serialization::serialize(stream, settingsDumpEnabled);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, motorsEnabled);
    ros::serialization::deserialize(stream, settingsDumpEnabled);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(motorsEnabled);
    size += ros::serialization::serializationLength(settingsDumpEnabled);
    return size;
  }

  typedef boost::shared_ptr< ::rover::Enabled_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover::Enabled_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Enabled
typedef  ::rover::Enabled_<std::allocator<void> > Enabled;

typedef boost::shared_ptr< ::rover::Enabled> EnabledPtr;
typedef boost::shared_ptr< ::rover::Enabled const> EnabledConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::rover::Enabled_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::rover::Enabled_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace rover

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rover::Enabled_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rover::Enabled_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rover::Enabled_<ContainerAllocator> > {
  static const char* value() 
  {
    return "944b9b58b23f7416adecf8816d3ed0ef";
  }

  static const char* value(const  ::rover::Enabled_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x944b9b58b23f7416ULL;
  static const uint64_t static_value2 = 0xadecf8816d3ed0efULL;
};

template<class ContainerAllocator>
struct DataType< ::rover::Enabled_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rover/Enabled";
  }

  static const char* value(const  ::rover::Enabled_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rover::Enabled_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool motorsEnabled\n\
bool settingsDumpEnabled\n\
\n\
";
  }

  static const char* value(const  ::rover::Enabled_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::rover::Enabled_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rover::Enabled_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.motorsEnabled);
    stream.next(m.settingsDumpEnabled);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Enabled_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover::Enabled_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::rover::Enabled_<ContainerAllocator> & v) 
  {
    s << indent << "motorsEnabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motorsEnabled);
    s << indent << "settingsDumpEnabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.settingsDumpEnabled);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROVER_MESSAGE_ENABLED_H

