obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.20
footprint: [[0.12,0.12], [-0.12,0.12], [-0.12,-0.12], [0.12,-0.12]]
inflation_radius: 0.35
observation_sources: scan
scan: {sensor_frame: /openni_depth_frame, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
